services:
  apistartkit:
    build: .
    volumes:
      - ./api:/app
      - ./sugarcane_model_v1.keras:/sugarcane_model_v1.keras
    ports:
      - "8000:8000"
    command: ["uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "8000"]
